language: node_js
sudo: false
node_js:
  - '4.2'

cache:
  directories:
    - trevi/node_modules
    - trevi/vendor/assets/components

before_script:
  - 'cd trevi'
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower karma grunt-cli jshint'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages

after_script:
  - 'grunt test'

branches:
  only:
    - master
    - develop

notifications:
  email:
    - tom.kim+travis@dramancompany.com
