language: node_js
sudo: false
node_js:
  - '4.2'

cache:
  directories:
    - trevi/node_modules
    - trevi/vendor/assets/components

cache: bundler

before_install:
  - cd trevi

  - rvm install 2.2.0
  - rvm use 2.2.0 --install --binary --fuzzy
  - ruby --version
  - rvm --version
  - bundle --version
  - gem --version

  - openssl aes-256-cbc -K $encrypted_288f18f07939_key -iv $encrypted_288f18f07939_iv
    -in config/secrets.tar.enc -out config/secrets.tar -d

  - tar xvf config/secrets.tar
  - pwd
  - ls

install:

before_script:
  - bundle install

  - which chromium-browser
  - export CHROME_BIN=/usr/bin/chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower karma grunt-cli jshint
  - npm install # install npm packages
  - bower install # install bower packages

script:
  - bundle exec rake
  - npm test

after_success:

after_failure:

after_script:

branches:
  only:
    - master
    - develop

notifications:
  email: false
    # - tom.kim+travis@dramancompany.com
