language: ruby
rvm:
  2.2.0

before_script:
  - 'cd trevi'
  - 'bundle install'

env:
  - SECRET_TOKEN='SECRETTOKENSECRETTOKEN'
  - SECRET_KEY_BASE='SECRETKEYBASESECRETKEYBASESECRETKEYBASE'


# language: node_js
# sudo: false
# node_js:
#   - '4.2'
#
# cache:
#   directories:
#     - trevi/node_modules
#     - trevi/vendor/assets/components
#
# before_script:
#   - 'which chromium-browser'
#   - 'cd trevi'
#   - 'export CHROME_BIN=/usr/bin/chromium-browser'
#   - 'export DISPLAY=:99.0'
#   - 'sh -e /etc/init.d/xvfb start'
#   - 'npm install -g bower karma grunt-cli jshint'
#   - 'npm install' # install npm packages
#   - 'bower install' # install bower packages
#
# after_script:
#
branches:
  only:
    - master
    - develop

notifications:
  email:
    - tom.kim+travis@dramancompany.com
