language: ruby
rvm: 2.2.0
before_script:
  - bundle install
before_install:
  - cd trevi
  - openssl aes-256-cbc -K $encrypted_e77f5b7e6948_key -iv $encrypted_e77f5b7e6948_iv
    -in config/secrets.yml.enc -out config/secrets.yml -d
branches:
  only:
    - master
    - develop
notifications:
  email:
    - tom.kim+travis@dramancompany.com
